#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    # Write your code here
    arr_sorted=sorted(arr)
    #print(arr)
    max_val=sum(arr_sorted[1:5])
    min_val=sum(arr_sorted[0:4])
    print(min_val,max_val)
    

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
