#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # print(s)
    # Write your code here
    if s[:2]=='12':
        if s[-2:]=='AM':
            s='00'+s[2:-2]
            
        else:
            s=s[:-2]
    else:
        if s[-2:]=='AM':
            s=s[:-2]
        else:
            hour=str(int(s[:2])+12)
            s=hour+s[2:-2]
    return(s)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
