#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'caesarCipher' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING s
#  2. INTEGER k
#

def caesarCipher(s, k):
    # Write your code here
    s_Ciphered=''
    for i in range(len(s)):
        char=s[i]
        print(char)
        #print(k)
        if char.isalpha():
            if char.isupper():
                char=chr((ord(char)-65+k)%26 +65)
            elif char.islower():
                char=chr((ord(char)-97+k)%26 +97)
        #print(char)
        s_Ciphered=s_Ciphered+char
    return(s_Ciphered)    
    
                       

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    s = input()

    k = int(input().strip())

    result = caesarCipher(s, k)

    fptr.write(result + '\n')

    fptr.close()
